<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function findAllPaginated($page, $limit)
    {
        $query = $this->createQueryBuilder("m")
            ->orderBy("m.last_name", "ASC")
            ->addOrderBy("m.first_name", "ASC")
            ->setMaxResults($limit)
            ->setFirstResult(($page-1)*$limit)
            ->getQuery();
        return $query->getResult();
    }
}
