CumtsMainBundle_holding:
    pattern:  /
    defaults: { _controller: CumtsMainBundle:Default:holding }
CumtsMainBundle_homepage:
    pattern:  /home
    defaults: { _controller: CumtsMainBundle:Default:index }
CumtsMainBundle_about:
    pattern:  /about
    defaults: { _controller: CumtsMainBundle:Default:page, content_name: 'about' }
CumtsMainBundle_get_involved:
    pattern:  /get-involved
    defaults: { _controller: CumtsMainBundle:Default:page, content_name: 'get-involved' }
CumtsMainBundle_membership_ext:
    resource: "@CumtsMainBundle/Resources/config/routing/membership.yml"
    prefix:   /membership
CumtsMainBundle_contact:
    pattern:  /contact
    defaults: { _controller: CumtsMainBundle:Contact:index }
CumtsMainBundle_contact_post:
    pattern:  /contact/send
    defaults: { _controller: CumtsMainBundle:Contact:contact }
    requirements: { _method: POST }
CumtsMainBundle_news_ext:
     resource: "@CumtsMainBundle/Resources/config/routing/news.yml"
     prefix:   /news
CumtsMainBundle_events_ext:
     resource: "@CumtsMainBundle/Resources/config/routing/event.yml"
     prefix:   /events
OrderlyPayPalIpnBundle:
     pattern: /paypal/ipn
     defaults: { _controller: CumtsMainBundle:Paypal:ipn }
CumtsMainBundle_paypal_init:
     pattern: /paypal/init/{id}
     defaults: { _controller: CumtsMainBundle:Paypal:init }
CumtsMainBundle_paypal_redirect:
     pattern: /paypal/redirect/{id}
     defaults: { _controller: CumtsMainBundle:Paypal:redirect }
CumtsMainBundle_paypal_complete:
     pattern: /paypal/complete/{id}
     defaults: { _controller: CumtsMainBundle:Paypal:complete }
CamdramUpdate:
        pattern: /cron/camdram
