parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     cumts
    database_user:     cumts
    database_password: holeWamye

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            25b60185c3dbc6198ecd1ca196274b66
