#ihoyes_image_manager:
#    resource: "@HoyesImageManagerBundle/Resources/config/routing.yml"
#    prefix:   /

CumtsAdminBundle:
    resource: "@CumtsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

CumtsMainBundle:
    resource: "@CumtsMainBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

HoyesImageManagerBundle:
    resource: "@HoyesImageManagerBundle/Resources/config/routing.yml"
    prefix:   /image