CumtsAdminBundle:
    resource: "@CumtsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

CumtsMainBundle:
    resource: "@CumtsMainBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
