security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_MEMBER: ROLE_USER
        ROLE_CURRENT: ROLE_MEMBER
        ROLE_COMMITTEE: [ROLE_ADMIN, ROLE_CURRENT]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [main, raven]
        main:
            entity: { class: Cumts\MainBundle\Entity\Member, property: auth_id }
        raven:
            id: raven_user_provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/.*
            raven: true
            logout: ~
            anonymous: true
            logout:
                path: /logout

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path ^/admin/.*, roles: ROLE_ADMIN }
        - { path ^/membership/raven.*, roles: IS_AUTHENTICATED_FULLY }
