CumtsMainBundle_news:
    pattern:  /
    defaults: { _controller: "CumtsMainBundle:News:index" }

CumtsMainBundle_news_show:
    pattern:  /{slug}
    defaults: { _controller: "CumtsMainBundle:News:show" }
