<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function findAllQuery($type = null)
    {
        $query = $this->createQueryBuilder("m")
            ->orderBy("m.last_name", "ASC")
            ->addOrderBy("m.first_name", "ASC")
            ->where("m.paid = true");
        if (is_numeric($type)) {
            $query->andWhere("m.membership_type = $type");
        }
        
        return $query->getQuery();
    }
}
