<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function findAllQuery($type = null)
    {
        $query = $this->createQueryBuilder("m")
            ->orderBy("m.last_name", "ASC")
            ->addOrderBy("m.first_name", "ASC");
        if (is_numeric($type)) {
            if ($type == Member::UNPAID) {
                $query->where("m.paid = false");
            }
            else {
                $query->where("m.membership_type = $type")
                    ->andWhere("m.paid = true");
            }
        }
        
        return $query->getQuery();
    }

    public function findPaidMember($auth_id)
    {
	return $this->createQueryBuilder("m")
		->where("m.auth_id = :auth_id")
		->where("m.paid = :paid")
		->setParameter('auth_id', $auth_id)
		->setParameter('paid', true)
		->getQuery()->getOneOrNullResult();
    }
}
