<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function findRandom($number)
    {
        $em = $this->getEntityManager();
        $rsm = new ResultSetMappingBuilder($em);
$rsm->addRootEntityFromClassMetadata('Cumts\MainBundle\Entity\Photo', 'p');
        $query = $this->getEntityManager()->createNativeQuery("select * from photos order by RAND() LIMIT ?", $rsm);
        $query->setParameter(0, $number);
       
        return $query->getResult();
    }
}
