<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function findRandom($number)
    {
        $rsm = new ResultSetMapping;
        $rsm->addEntityResult('Cumts\MainBundle\Entity\Photo', 'p');
        $query = $this->getEntityManager()->createNativeQuery("select * from photos order by RAND() LIMIT ?", $rsm);
        $query->setParameter(1, $number);
        return $query->getResult();
    }
}
