<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function subtractItems($id, $quantity)
    {
        $product = $this->findOneById($id);
        
        $query = $this->createQueryBuilder('p')
            ->update();
        
        if ($product->getNumberAvailable() !== NULL) {
             $query->set('p.number_available', 'p.number_available - :quantity');
        }
        
        $query->set('p.number_sold', 'p.number_sold + :sold')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->setParameter('quantity', $quantity)
            ->setParameter('sold', $quantity)
            ->getQuery()->execute();
    
        
    }

}
