<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function subtractItems($id, $quantity)
    {
        return $this->createQueryBuilder('p')
            ->set('p.number_available', 'p.number_available - :quantity')
            ->set('p.number_sold', 'p.number_sold + :quantity')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->setParameter('quantity', $quantity)
            ->getQuery()->execute();
    }

}
