<?php

namespace Cumts\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRoleRepository extends EntityRepository
{
    public function getUnknownCamdramIds()
    {
        $q = $this->createQueryBuilder('r')
        ->select('r.camdram_id')
        ->where('r.member IS null')
        ->distinct()
        ->getQuery();
        return $q->getResult();
    }
    
    public function addMemberForCamdramId($member, $camdram_id) {
        $q = $this->getEntityManager()->createQuery('update Cumts\MainBundle\Entity\ShowRole m set m.member = :m where m.camdram_id = :id');
        $q->setParameter('id', $camdram_id);
        $q->setParameter('m', $member);
        $q->execute(); 
    }
}
