admin_members_show:
    pattern:  /{id}/show
    defaults: { _controller: "CumtsAdminBundle:Member:show" }

admin_members_new:
    pattern:  /new
    defaults: { _controller: "CumtsAdminBundle:Member:new" }

admin_members_create:
    pattern:  /create
    defaults: { _controller: "CumtsAdminBundle:Member:create" }
    requirements: { _method: post }

admin_members_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CumtsAdminBundle:Member:edit" }

admin_members_update:
    pattern:  /{id}/update
    defaults: { _controller: "CumtsAdminBundle:Member:update" }
    requirements: { _method: post }

admin_members_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CumtsAdminBundle:Member:delete" }
    requirements: { _method: post }

admin_members_ldap:
    pattern:  /ldap/{crsid}
    defaults: { _controller: "CumtsAdminBundle:Member:ldap" }
  
admin_members_check:
    pattern:  /check
    defaults: { _controller: "CumtsAdminBundle:Member:check" }

admin_members_print:
    pattern: /print
    defaults: { _controller: "CumtsAdminBundle:Member:print", filter: 0 }

admin_members_export:
    pattern: /export
    defaults: { _controller: "CumtsAdminBundle:Member:export" }

admin_members:
    pattern:  /{page}/{filter}
    defaults: 
        _controller: "CumtsAdminBundle:Member:index"
        page: 1
        limit: 25
        filter: 0
    requirements:
        page: \d+
        limit: \d+
