CumtsAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: CumtsAdminBundle:Default:index }
CumtsAdminBundle_members:
    resource: "@CumtsAdminBundle/Resources/config/routing/member.yml"
    prefix:   /members
CumtsAdminBundle_news:
    resource: "@CumtsAdminBundle/Resources/config/routing/news.yml"
    prefix:   /news
CumtsAdminBundle_events:
    resource: "@CumtsAdminBundle/Resources/config/routing/event.yml"
    prefix:   /events
CumtsAdminBundle_ipnorders:
    resource: "@CumtsAdminBundle/Resources/config/routing/paypal-orders.yml"
    prefix:   /paypal/orders
CumtsAdminBundle_shows:
        resource: "@CumtsAdminBundle/Resources/config/routing/show.yml"
        prefix:   /shows
