parameters:
#    cumts_admin.example.class: Cumts\AdminBundle\Example

services:
#    cumts_admin.example:
#        class: %cumts_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
